
POST http://localhost:4001/user/login
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "email":"chimdi4332@gmail.com",
    "password":"comon@2"
}
###
POST http://localhost:4001/user/register
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "email":"chimdi4332@gmail.com",
    "password":"common@2",
    "phone_number":"+2348150740406",
    "Interest":"FOOTBALL"
}
# ###
# POST http://localhost:4001/user/update-profile
# Authorization: Bearer eTYsv...
# Content-Type: application/json

# {
#     "user_id":"chimdi4332@gmail.com",
#     "city":"campinas"
# }
###
POST http://localhost:4001/user/v-registration
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "user_id":"e7b25f40-cf1b-4d7c-b297-cce420642c68",
    "token":"803002"
}
###
POST http://localhost:4001/user/r-registration
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "user_id":"9b092adc-fd9d-4c18-96e5-71665fbeace2",
    "email":"chimdi4332@gmail.com"
}
###
POST http://localhost:4001/user/forgot-password
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "email":"chimdi4332@gmail.com"
}
###
POST http://localhost:4001/user/v-forgot-password
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "email":"chimdi4332@gmail.com",
    "token":"371087",
    "password":"common@2"
}
###
POST http://localhost:4001/user/r-forgot-password
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "email":"chimdi4332@gmail.com"
}
###
POST http://localhost:4001/user/update-profile
Authorization: Bearer eTYsv...
Content-Type: application/json

{
    "user_id":"9b092adc-fd9d-4c18-96e5-71665fbeace2",
    "email":"chimdi4332@gmail.com",
    "password":"common@2"
}
